// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDroGuXtn6vUltgUfLvGjoZWxtlHD5FIfk',
    appId: '1:193818578476:web:5e7f4eed87d422bb1bcb89',
    messagingSenderId: '193818578476',
    projectId: 'helthcare-2025',
    authDomain: 'helthcare-2025.firebaseapp.com',
    storageBucket: 'helthcare-2025.firebasestorage.app',
    measurementId: 'G-VNYN39VW39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBTktNKa_WHm1TJZTNLnm_z6ojA7XrQDA',
    appId: '1:193818578476:android:4a2dfea3c2c037d51bcb89',
    messagingSenderId: '193818578476',
    projectId: 'helthcare-2025',
    storageBucket: 'helthcare-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAanQM054FUueZJAUe9duzFFV6q8JVUHR8',
    appId: '1:193818578476:ios:42a6975a34fc489d1bcb89',
    messagingSenderId: '193818578476',
    projectId: 'helthcare-2025',
    storageBucket: 'helthcare-2025.firebasestorage.app',
    iosBundleId: 'com.example.helthcare',
  );
}
